### ISSUE TITLE
Accessing lightened/darkened colors

### ISSUE THREAD

**Issue by windom** [tachyons-css/react-native-style-tachyons#10]
Hi!
First, thanks for this fantastic library!
I think it would be useful if you would export the allColors object too. For instance I would like to use the darkened version of a color from the palette for a TouchableHighlight's underlayColor .
What do you think?

**Comment by fab1an** [comment]
Good idea, added in 2.3.0.

**Comment by windom** [comment]
Awesome, that was fast :)
