### ISSUE TITLE
bug: styles values are undefined on the first load

### ISSUE THREAD

**Issue by souravdasslg** [tachyons-css/react-native-style-tachyons#101]
Im facing this strange issue. After the app starts, styles comes as `undefined` for some unknown reason. Once the component re-render the styles are loaded. 
```typescript
import React, { useMemo } from 'react';
import { View } from 'react-native';
import { styles as s } from 'react-native-style-tachyons';

const styles = {
  padding: {
    'xx-small': { padding: 2 },
    'x-small': s.pa1,
    small: s.pa2,
    normal: s.pa3,
    large: s.pa4,
    'x-large': s.pa5,
    'xx-large': s.pa6,
  },
};

export interface SpacerProps {
  fill?: boolean;
  size?: keyof typeof styles.padding;
}

export function Spacer({ fill, size = 'normal' }: SpacerProps) {
  console.log('spacer style', styles.padding[size]);
  const style = useMemo(() => [styles.padding[size], fill && s.flex], [size, fill]);
  console.log('spacer memo style', style);
  return <View style={style} />;
}
```

![Screenshot 2023-06-17 at 11 19 17 PM](https://github.com/tachyons-css/react-native-style-tachyons/assets/9268592/1788c9a3-0d98-4c87-97b1-f58cd39044b5)

How to reproduce this :
Create a new react native project
Setup react-native-style-tachyons
Styling would not work in first go. App reload wont help. Components needs to be re-rendered.

**Comment by fab1an** [comment]
Can you please downgrade to 4.2.3 and see if that issue persists?

**Comment by souravdasslg** [comment]
I tried downgrading, but pervious ~3 version. The issue seems to persist.

**Comment by fab1an** [comment]
Ok, can you show your `NativeTachyons.build(...)`

**Comment by souravdasslg** [comment]
This is what my App.tsx looks like.
![Screenshot 2023-06-19 at 10 10 56 AM](https://github.com/tachyons-css/react-native-style-tachyons/assets/9268592/34ca766a-b9a6-4d5a-b65b-868e135d084a)

**Comment by souravdasslg** [comment]
I suspected the same thing about my app, so I have put the build command in the index.js even before importing the App file. I see effects are same everywhere.

**Comment by fab1an** [comment]
Do you have some custom babel config with plugins that might change the order? have you tried running console.log to see whether the order is correct.

**Comment by fab1an** [comment]
@souravdasslg Did you have any chance to look further into this? You are the only one reporting such an issue, so I'm pretty sure it must be some weird react/babel config issue.

**Comment by fab1an** [comment]
@souravdasslg Since I haven't heard back from you I am closing this.
