### ISSUE TITLE
Support for sharing web/RN styles (brainstorming)

### ISSUE THREAD

**Issue by tribou** [tachyons-css/react-native-style-tachyons#12]
I'm new to tachyons and not even sure if this is possible; but by having immutable, predefined CSS class names, there might be some unique opportunities somewhere.

Is it feasible to add support for sharing styling across React Native and browser?

The ideas from other libraries I've seen so far are:

1) Wrapping components:
```js
export default stylings(styles)(MyComponent)
```

2) Style-only components:
```js
render () {
  return (
    <StyleOnlyComponent>
      <MyComponent />
    </StyleOnlyComponent>
  )
}
```

3) Separate stylesheet:
```js
import styles from './MyComponent'
```

4) [Stripping inline styles on web](https://github.com/js-next/react-style-webpack-plugin)

Unfortunately, I don't know if any current solution allows you to keep styles in the same file...and if it did, I'm guessing you would need to use `if/then` to return either HTML or RN components.

I'm not advocating any particular one of these examples but brainstorming if the immutable classes could be organized in such a way to enable a new paradigm of organizing shared web and React Native styles for a better design/dev experience.

**Comment by fab1an** [comment]
The problem with sharing styles across the browser isn't the organization of files, that can be done with babel-plugins, webpack-plugins and the like, but that the browser and react-native follow a different styling model.

Example: In browser it's possible to set a `font-size` on a `<div>` and it will propagate down. In react-native styles aren't propagated and setting a `font-size` is only possible on a `<Text>` element.

**Comment by fab1an** [comment]
And the second questions is: How far can a design for mobile be reused on the web at all, since it's made for a different view-port?

**Comment by fab1an** [comment]
@tribou See this project: https://github.com/necolas/react-native-web#why
