### ISSUE TITLE
How do you define a fontFamily?

### ISSUE THREAD

**Issue by kwokhou** [tachyons-css/react-native-style-tachyons#17]
Is there a way to define the fontFamily? Maybe during `NativeTachyons.build`? something similar to defining the color palette

So this
`<Text style={[{ fontFamily: 'Iowan Old Style' }]}>Hello World</Text>`
can be turn into 
`<Text style={[s.ff]}>Hello World</Text>`

**Comment by fab1an** [comment]
Not yet, but I'm open for it. I would probably do it with a prefix though:

```
NativeTachyons.build({
   fonts: {
      iowan: 'Iowan Old Style'
   }
}, StyleSheet);
```

And then

```<Text style={[s.ff_iowan]}>Hello World</Text>```

Do you like that?

**Comment by kwokhou** [comment]
Yes, that's even better

**Comment by fab1an** [comment]
I added this. Could you take some time to star this package on npm? https://www.npmjs.com/package/react-native-style-tachyons

(I have a second, defunct package there which still get's downloads because it has more stars than this one)

**Comment by kwokhou** [comment]
Definitely. done.
