### ISSUE TITLE
usage without NativeTachyons.build?

### ISSUE THREAD

**Issue by vonovak** [tachyons-css/react-native-style-tachyons#18]
hi! thanks for the lib. I got here mainly because of looking for shortcuts for the react native styles, such as `<View style={[s.flx_row]}>`.

As per the docs, there is the need to call the init method before first use: `NativeTachyons.build({}, StyleSheet);` when I built a android app in release mode I noticed the call takes ~50ms, which is not too much (although more than expected) but I was thinking that for usage of my kind, such call shouldn't really be necessary. Just an idea.

**Comment by fab1an** [comment]
50ms is definitely a bit too much. I would look into it, but my time is a bit limited at the moment. You could try and profile what's taking so long. Thanks.

**Comment by fab1an** [comment]
@vonovak Could you show me how you profiled the call, so I can try to reproduce this?

**Comment by vonovak** [comment]
I used Date objects. Apparently there are better ways to do this, like `performance.now()` but that isn't available on RN

**Comment by fab1an** [comment]
Please checkout the new version `3.0` I just published, you should see a 100% improvement in init-speed.

**Comment by fab1an** [comment]
@vonovak Could you redo your profiling?
