### ISSUE TITLE
incompatibility with react-stamp

### ISSUE THREAD

**Issue by finnfiddle** [tachyons-css/react-native-style-tachyons#19]
Hi there, thanks for making this module.
However, the `NativeTachyons.wrap` HOC isn't compatible with [react-stamp](https://github.com/stampit-org/react-stamp).
```
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
```
This function in particular is invalidating the component Im passing to the HOC if its created like this instead of using the es6 class syntax (I haven't tried es5 syntax):
```
export default NativeTachyons.wrap(stamp(React).compose({
  ...
}));
```
So for the moment I have to use the `style` prop instead of the `cls` prop. How necessary is this validation step?

**Comment by fab1an** [comment]
Hi, the wrapping is only necessary if you want to use the `cls` String. The string is checked, if that is what you mean by 'validation step'.

Could you give me a stacktrace of your Error?

**Comment by finnfiddle** [comment]
yes I'd like to use cls for colors and also its more expressive imo. not sure how to get the stack trace as text but heres a screenshot 
![screen shot 2016-11-16 at 2 43 31 pm](https://cloud.githubusercontent.com/assets/4628721/20347791/4327f636-ac0b-11e6-962e-9ec3ffb3951e.png)

**Comment by fab1an** [comment]
I've looked into this, but can't find a solution. I think it is a problem with react-stamp, since that messes with React's Component constructor.

**Comment by finnfiddle** [comment]
You're right sorry its actually related to babel, not specifically your module. Ill see if I can find a way to make it work nicely

**Comment by fab1an** [comment]
Ok, i'll close this then.
