### ISSUE TITLE
@NativeTachyons.wrap not effect

### ISSUE THREAD

**Issue by qqke** [tachyons-css/react-native-style-tachyons#20]
import NativeTachyons from "react-native-style-tachyons";

@NativeTachyons.wrap
export default class ProfileScreen extends Component {
...
                <View cls="ba jcfs pa2">
                    <Text cls="white tc">
                        Something
                    </Text>
                </View>
...
but it cause error like this:
style 'ba' not found

**Comment by fab1an** [comment]
Try:

```
export default wrap(class ProfileScreen extends Component{
})
```
