### ISSUE TITLE
Opacity suffix translates badly

### ISSUE THREAD

**Issue by 0x6e6562** [tachyons-css/react-native-style-tachyons#21]
Adding an opacity suffix appears to translate to an invalid property.

For example, this class

```jsx
<View cls="bg-grey-10">
```

Causes the following issue:

```
Warning: Failed prop type: Invalid prop `backgroundColor` supplied to `RCTView`: grey_10
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "flex": 1,
  "marginVertical": 64,
  "marginHorizontal": 8,
  "borderWidth": 1,
  "backgroundColor": "grey_10"
}
    in RCTView (created by View)
    ...
```

Have I used the wrong syntax?

**Comment by fab1an** [comment]
You are using the correct syntax.

At the moment the variants with opacities are only generated for the colors specified in the palette, not for the "default" colors that react-native supported. This is a relict from a previous version.

You should be able to work around it by adding this to your palette:
```
colors: {
      palette: {
         grey: "grey",
      }
   }
```

**Comment by 0x6e6562** [comment]
Hey @fab1an  - many thanks for the heads up - this works perfectly :-)

**Comment by fab1an** [comment]
Glad to hear!
