### ISSUE TITLE
cls wrapper appears to overwrite other style definitions 

### ISSUE THREAD

**Issue by 0x6e6562** [tachyons-css/react-native-style-tachyons#22]
I'm trying to build use the DrawerNavigation component from [ex-navigation](https://github.com/exponentjs/ex-navigation) in conjunction with the `cls` wrapper. What _appears_ to be happening is that the definitions specified in the wrapped component are rendered correctly. But after introduced the wrapping of the child component, the rendering of the parent navigation component appears to have been disabled. It's as if the style definitions of the parent have been overwritten and effectively nulled out.

Am I potentially wrapping the child component incorrectly? Or would a running example help to illustrate the issue?

**Comment by 0x6e6562** [comment]
To illustrate the issue I'm seeing, I've created a basic example (see below).

The behavior I am seeing is that with the `NativeTachyons.wrap(...)` commented out, the navigation will render correctly (according to the styles baked into it). Without the wrapper, the `cls` attribute has not effect, which is to be expected.

However, when I comment the wrapper back in, the `cls` caused the target element to get rendered correctly, but as a side effect, the navigation rendering is lost:

```js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import {
  createRouter,
  DrawerNavigation,
  DrawerNavigationItem,
  NavigationProvider,
  StackNavigation,
} from '@exponent/ex-navigation';


import NativeTachyons from "react-native-style-tachyons";

//HomeScreen = NativeTachyons.wrap(
  class HomeScreen extends React.Component {
    static route = {
      navigationBar: {
        title: 'Home',
      }
    }

    render() {
      return (
        <View style={styles.content}>
          <Text>WITHOUT TACHYONS</Text>
          <Text cls='red'>WITH TACHYONS</Text>
        </View>
      )
    }
  }
//)

const Router = createRouter(() => ({
  home: () => HomeScreen,
}));

class AppContainer extends React.Component {

  render() {
    return (
      <NavigationProvider router={Router}>
      <DrawerNavigation
        id='main'
        initialItem='home'
        drawerWidth={300}
        renderHeader={this._renderHeader}>
        <DrawerNavigationItem
          id='home'
          selectedStyle={styles.selectedItemStyle}
          renderTitle={isSelected => this._renderTitle('Home', isSelected)}
          >
          <StackNavigation
            id='home'
            initialRoute={Router.getRoute('home')}/>
        </DrawerNavigationItem>

      </DrawerNavigation>
      </NavigationProvider>
    );
  }

  _renderHeader = () => {
    return (
      <View style={styles.header}>
      </View>
    );
  };

  _renderTitle(text: string, isSelected: boolean) {
    return (
      <Text style={[styles.titleText, isSelected ? styles.selectedTitleText : {}]}>
        {text}
      </Text>
    );
  };
}


const styles = StyleSheet.create({

  content: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1
  },

  header: {
    height: 20
  },

  selectedItemStyle: {
    backgroundColor: 'blue'
  },

  titleText: {
    fontWeight: 'bold'
  },

  selectedTitleText: {
    color: 'white'
  }
});

AppRegistry.registerComponent('cls_test', () => AppContainer);

```

**Comment by 0x6e6562** [comment]
So I've found out what the issue was. Basically it is done to the way that static properties of an imported component were being initialized in conjunction with wrapping the component with Tachyons.

So rather than doing this:

```js
export default HomeScreen = NativeTachyons.wrap(
  class HomeScreen extends React.Component {
    static route = {
      navigationBar: {
        title: 'Home',
      }
    }
)
```

You can wrap the component and apply the static properties thusly:

```js
export default HomeScreen = NativeTachyons.wrap(HomeScreen);

HomeScreen.route = {
  navigationBar: {
    title: 'Home',
  }
}
```

Moreover you can also run into other symbol export issues when using decorators. So instead of using `@connect` from redux you can subscribe to the store (keeping Tachyons) like this:

```js
const WrappedHomeScreen = NativeTachyons.wrap(HomeScreen);
export default HomeScreen = connect(data => WrappedHomeScreen.getDataProps(data))(WrappedHomeScreen);
```

**Comment by fab1an** [comment]
Thanks for investigating this, I didn't have time to look at it yet.
