### ISSUE TITLE
Add properties for flexGrow, flexShrink, flexBasis

### ISSUE THREAD

**Issue by peacechen** [tachyons-css/react-native-style-tachyons#23]
as documented on the RN page
https://facebook.github.io/react-native/docs/layout-props.html

**Comment by fab1an** [comment]
Hi @peacechen,

I have not implemented, as I haven't found a need for them in any layout yet, and I want to keep `tachyons` as simple as possible.

If you want to advance this issue, send me examples for layouts that require said properties.

**Comment by peacechen** [comment]
Thanks for the reply.  Great library you've shared!  I'll update when I have a concrete example.  I've been wrestling with RN flex layout to get it to do what I'd like.  I believe flexGrow could be handy after tinkering with this realtime tool:
http://blog.krawaller.se/posts/a-react-app-demonstrating-css3-flexbox/

**Comment by peacechen** [comment]
[Liquid layout](http://maxdesign.com.au/articles/liquid/) is a use case for flexGrow.  3 columns taking up the entire width of the page. Left or right may be fixed width or size to their contents.  Center column takes up the remaining space regardless of its content (including no content).

`[ Left ]  [ _________ Center _________ ]  [ Right ....]`

I've tried accomplishing that without flexGrow but it was incredibly convoluted and didn't fully achieve what I wanted.

I can't give good examples for flexShrink and flexBasis.  It would make your library more flexible to include them because other people could have valid use cases.

**Comment by fab1an** [comment]
Hm, but why don't you use 

```jsx
<View cls="flx-row"/>
    <Left cls="w2/>
    <Middle cls="flx-i/>
    <Right cls="w2/>
</View>
```

**Comment by fab1an** [comment]
Have you checked my example out?

**Comment by peacechen** [comment]
Thanks for the recommendation.  That works well.

`space-between` produces a similar effect:
```
<View cls="flx-row, jcsb"/>
    <Left/>
    <Center/>
    <Right/>
</View>
```

The difference is that the Center width isn't stretched, but it's placed properly and will size as large as its contents.  My use case was more complex (one piece was a View wrapping other components) which probably confused me.

**Comment by fab1an** [comment]
Can I close this?

**Comment by peacechen** [comment]
Yes thanks for your help.
