### ISSUE TITLE
color styling doesn't apply to <Text>

### ISSUE THREAD

**Issue by peacechen** [tachyons-css/react-native-style-tachyons#24]
Applying color styles to Text components doesn't work for me.  Example:

```
import { styles as s } from "react-native-style-tachyons";

...
render() {
	return (
		<Text style={[s.f4, s.white]}>My Text</Text>
	);
}
```

f4 font size is applied, but the color is the default black instead of white.  If I create a stylesheet and add it to the `style` prop, it changes the color.  Am I using it correctly?

**Comment by fab1an** [comment]
In order to set colors via the property instead of `cls=` you have to add them to the palette.
