### ISSUE TITLE
Height & width granularity

### ISSUE THREAD

**Issue by peacechen** [tachyons-css/react-native-style-tachyons#25]
The jump from 4 to 5 on the height/width scale is 8 rem to 16 rem.  Often the layout needs finer granularity than that.  12 rem would work well in many cases.  Is there a way to add them (e.g. h3 + h4 = 12 rem) using the existing tachyons library?

**Comment by fab1an** [comment]
You can add up custom sizes using the `sizes` exports:

```jsx
import { sizes } from "react-native-style-tachyons"

...
<View style={{height: sizes.h3 + sizes.h4}}/>
```

I use this myself, it's not ideal, but I think opening the scale for "values-in-between" would endanger the consistency you get out of the box right now.

**Comment by ms88privat** [comment]
I'm using this awesome lib now for two projects (but still in the early development phase). I run into the same problem a couple of times...

What is the reason behind the border-radius value is only from 1 to 4?

**Comment by fab1an** [comment]
@ms88privat: Do you need larger values or more granular values? The scale corresponds to the tachyons.css project, and one idea behind it is to have fewer values, but carefully chosen values, so that the non-designers have it easy to create a pretty layout.

**Comment by fab1an** [comment]
Out of curiosity: which `rem` base value are you using. And are you on phone or tablet?

**Comment by ms88privat** [comment]
For the border-radius I need larger ones. Rem: `Dimensions.get('window').width > 340 ? 18 : 16,`. But let me play with it, never done it before.

**Comment by peacechen** [comment]
I've found that I also need larger max values in addition to granularity.  While I could change the rem value, that affects sizing globally and I require a few select items to be larger.

**Comment by peacechen** [comment]
I propose adding linear rem units for each sizing parameter.  For example, in addition to w1-w5  for 1-16 rems, wr1-wr32 would indicate width in rems from 1-32.  The reduced selection of w1-w5 doesn't really simplify things for designers IMHO.  Content isn't always sized in powers of 2; layouts regularly have arbitrary component widths.

**Comment by fab1an** [comment]
I disagree. The spacing scale is how it is because it prevents many off-by-one-pixel or off-by-one rem errors. This has been a key to the original tachyons.css success in the last years.

I won't add linear rem units, sorry.

**Comment by fab1an** [comment]
I will checkout `br5` (border-radius of `2em`) and possibly add that.

**Comment by peacechen** [comment]
Our app requires larger values across the board and finer granularity.  It sounds like that's not in line with your vision for RNST, and if there's no chance of adding those features, I may end up forking the project and release it under another package name.  I prefer not to since there's a maintenance cost and it can be difficult sync'ing fixes and features. Will wait to see how far we can use this library before the pain points become too great.  Appreciate the work you've put into this 👍

**Comment by fab1an** [comment]
Sound reasonable.

I didn't invent the tachyons scale, it existed years before the react-native port. It was designed with usability and readability of text in mind. I think larger values should be done with `flx-i`, but maybe I'll add w6, w7. 
I think adding linear values will compromise the whole idea.

I'll keep this issue open nevertheless, so that more people can weight in this discussion.

**Comment by peacechen** [comment]
Definitely understand the rationale for adopting the tachyons scale.  Consider this: the difference between w1 and w2 is 1 rem, so to say that 1 rem is too fine a granularity for pixel alignment isn't convincing.

32rem for w6 would help.  If that's too big for some cases, people can opt not to use it.

**Comment by fab1an** [comment]
I added an additional step for width, heights, margins, padding and border-radius in `3.1.0` that i just published.
