### ISSUE TITLE
undefined is not an object (evaluating 'navigator.userAgent.toLowerCase')

### ISSUE THREAD

**Issue by twavis** [tachyons-css/react-native-style-tachyons#26]
Hello and thanks for the great package! I like the idea of tachyons and the scaling text size was the icing on the cake. I ran into a problem though and can't sort out what is going wrong.

The error is thrown when the app is not connected to debugger. It occurs even with a release build which is very problematic. 

useColors in browser.js is checking navigator.userAgent.toLowerCase to determine if colors can be used in debug console when Tachyons attempts to create the debug function https://github.com/tachyons-css/react-native-style-tachyons/blob/master/lib/index.js#L66

My theory is that I am loading the tachyons package before react-native and thus the navigator string isn't initiated but every idea I've tried hasn't made a difference.

Do you have any insight on how to circumvent/fix this? Thanks.

**Comment by fab1an** [comment]
Which version of `debug` is being used, could you try downgrading to `2.3.3`?

**Comment by twavis** [comment]
npm install debug@2.3.3 fixed it... I didn't explicitly have any version of debug installed in the project but eslint was using 2.4.1 according to dependency tree...

Thank you. I've been trying to sort this longer than I like to admit :)

**Comment by fab1an** [comment]
@twavis I know, `npm`s versions can be a PITA. :/ 

Glad it works for you now.

**Comment by fab1an** [comment]
@twavis If you have the time please uninstall debug, and install the new version 3.0.3 I just published. It should work without an explicit version now.

**Comment by twavis** [comment]
@fab1an I just had the opportunity to confirm the 3.0.3 update works in having to explicitly define a debug version. Thanks again!
