### ISSUE TITLE
Access color from tachyons [feature request]

### ISSUE THREAD

**Issue by vincent-louis** [tachyons-css/react-native-style-tachyons#27]
Wich could able to access the computed color like how we able to access sizes from tachyons, appreciate much

**Comment by fab1an** [comment]
RNT since v3 doesn't compute colors anymore, it just passes the names to react-native. If you need values for the names I suggest you look into this library: https://www.npmjs.com/package/color

**Comment by vincent-louis** [comment]
Thanks for recommending that package, it was very useful.
I could export an object that contains all color code mapping, and import to the module when needed,
just fell like doing double work importing twice, since tachyons already have the color code I need and I still have to import another file. no prob, cheers, and many thanks
