### ISSUE TITLE
NativeTachyons.wrap will not style "renderHeader"

### ISSUE THREAD

**Issue by stefnnn** [tachyons-css/react-native-style-tachyons#30]
I wrap a class, which contains a ListView, with  ```@NativeTachyons.wrap```. However, the ListViews' renderHeader output will not be styled. 

Strangely enough, reactWrapper._recursiveStyle is called with the output from renderHeader, but the transformed elementTree does not seem to be used in the actual output.

Am I doing something wrong or is this a shortcoming of the wrapper?

```javascript
import React, { Component } from 'react'
import { Text, ListView, StyleSheet } from 'react-native'
import NativeTachyons from 'react-native-style-tachyons'
NativeTachyons.build({}, StyleSheet);

@NativeTachyons.wrap
export default class Example extends Component {
  render() {
    const data = [1,2,3,4]
    const dataSource = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 })
    ds = dataSource.cloneWithRows(data)
    const renderHeader = () => (<Text cls="b">Header</Text>)
    const renderRow = (rowData) => (<Text key={rowData} cls="green">{rowData}</Text>)
    return (
      <ListView dataSource={ds} renderHeader={renderHeader} renderRow={renderRow} />
    )
  }
}
```

**Comment by fab1an** [comment]
How do you apply the wrapper, I haven't seen the decorator usage "@NativeTachyons.wrap" before.
Does it work when you call the function normally?

**Comment by stefnnn** [comment]
It behaves identically. 

```javascript
export default NativeTachyons.wrap(
  class Example extends Component {
    render() {
      const data = [1,2,3,4]
      const dataSource = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 })
      ds = dataSource.cloneWithRows(data)
      const renderHeader = () => (<Text cls="b">Header</Text>)
      const renderRow = (rowData) => (<Text key={rowData} cls="green">{rowData}</Text>)
      return (
        <ListView dataSource={ds} renderHeader={renderHeader} renderRow={renderRow} />
      )
    }
})
```

**Comment by fab1an** [comment]
I think you have to wrap the header as well.

**Comment by stefnnn** [comment]
I'm not sure how I'd do that. NativeTachyons.wrap only accepts a class, no?

What would work of course, is to create a HeaderComponent and wrap this one. But that often is overkill for a simple header.

I experimented with another solution, where I changed NativeTachyons.wrap to accept both a class or a JSX-Element. Now I can call

```javascript
const renderHeader = () => (NativeTachyons.wrap(<Text cls="b">Header</Text>))
```

And it will work. But I might be missing something else in the first place.

**Comment by fab1an** [comment]
You have to use a HeaderComponent, yes. When the output returned by ListView resolves the entire child-tree it should works with your original example as well, though. It might have to do with react-optimizations like `babel-plugin-transform-react-constant-elements`.

**Comment by stefnnn** [comment]
I'm not using ```babel-plugin-transform-react-constant-elements```, but something along these lines might be causing it. Let me know if you can reproduce the case. If so, I'm happy to submit a PR with the new wrapper as outlined above. Works well for me.

**Comment by fab1an** [comment]
Please send your PR.

**Comment by fab1an** [comment]
#32 included.
