### ISSUE TITLE
Underline text property

### ISSUE THREAD

**Issue by peacechen** [tachyons-css/react-native-style-tachyons#35]
Similar to the `b` property (fontWeight: bold) and `i` (fontStyle: italic), it would be handy to be able to set an underline `u` property:
[textDecorationLine enum('none', 'underline', 'line-through', 'underline line-through')](https://facebook.github.io/react-native/docs/text.html)

**Comment by fab1an** [comment]
Could you do a PR?

My preferred names are the ones taken here: http://tachyons.io/docs/typography/text-decoration/

`strike`, `underline`

**Comment by peacechen** [comment]
Would your preference look like `s.strike` and `s.underline` in use?  Just want to make sure since bold is `s.b` and italics `s.i`

**Comment by fab1an** [comment]
Yes, I'd stay in line with the CSS here. Also italics and bold are more commonly used. So `b, i, underline` and `strike`

**Comment by fab1an** [comment]
Did you get around to do this?

**Comment by peacechen** [comment]
Apologies for the delay, have had other tasks pile up.  Hope to get to this.

**Comment by fab1an** [comment]
Ok. By the way, I realized I confused `text-decoration-line` with `text-decoration` in my argument above.

**Comment by fab1an** [comment]
I'll close this in favor of a PR.
