### ISSUE TITLE
Border thickness

### ISSUE THREAD

**Issue by 0x6e6562** [tachyons-css/react-native-style-tachyons#38]
How do you set the border thickness to something greater than 1?

To set thickness to say 2, I've tried:

* ba2
* ba_2
* ba-2
* ba--2

But none of these are legal properties.

**Comment by fab1an** [comment]
There is currently no way to change border-thickness. I argue that it is not needed in 99% percent of use-cases.

**Comment by 0x6e6562** [comment]
Fair enough - keep it simple and if people need to do funky things they can fall back to the standard style properties.
