### ISSUE TITLE
"document is not defined" using RN tachyons 3.3.2

### ISSUE THREAD

**Issue by peacechen** [tachyons-css/react-native-style-tachyons#41]
This error appeared after upgrading to 3.3.2:  "Can't find variable: document"

Stack trace shows
index.js : 66
debug.js : 119
browser.js : 49

useColors() references document

**Comment by fab1an** [comment]
We had this problem with debug already. Could you check this issue out: #26

**Comment by peacechen** [comment]
RN tachyons' package.json has the debug dependency set to `^2.6.4`.  The one installed in my local node_modules is 2.6.5.  Is there a specific version I should use?

**Comment by fab1an** [comment]
Thanks. I went one step further and removed the dependency alltogether, since it made problems twice already.
