### ISSUE TITLE
Add style for image's tintColor

### ISSUE THREAD

**Issue by mordaha** [tachyons-css/react-native-style-tachyons#53]
Maybe tco-black or itc-black or something

**Comment by fab1an** [comment]
Could you do a PR? 

Similarly to `bg-` for background and `b-` for border-color, I want to use a prefix of `tint-` for the tint-color.

1. Here's the functionality for the background-color-functionality: https://github.com/tachyons-css/react-native-style-tachyons/blob/master/src/reactWrapper.js#L62
2. You need to a test here: https://github.com/tachyons-css/react-native-style-tachyons/blob/master/test/index_spec.js#L90
3. and update the README.

Thank you.

**Comment by mordaha** [comment]
Here you are #54 :)
