### ISSUE TITLE
Bug: wrapped component can return null

### ISSUE THREAD

**Issue by mordaha** [tachyons-css/react-native-style-tachyons#59]
Then recursiveStyle function failed

https://github.com/tachyons-css/react-native-style-tachyons/blob/master/src/reactWrapper.js#L34

```
function recursiveStyle(elementsTree) {
    // here elementsTree === null and next line throws
    const { props } = elementsTree;
```

should be something like

```
function recursiveStyle(elementsTree) {
    if(!elementsTree) return elementsTree;
    const { props } = elementsTree;
```

I can send PR

**Comment by fab1an** [comment]
What is your usecase?

**Comment by euroclydon37** [comment]
Was a PR created for this? I have components that render null if a certain prop is true. For example, and offline banner that connects to redux state renders react elements when the app is offline, but renders `null` if the app is online.

With this bug, I either have to use raw styling or make every page in my app that consumes this component handle the conditional rendering.

**Comment by mordaha** [comment]
sorry i was too short of time and just used `return <View />' instead of `return null` :)

**Comment by euroclydon37** [comment]
No worries.
