### ISSUE TITLE
Adding separate config for font rem

### ISSUE THREAD

**Issue by peacechen** [tachyons-css/react-native-style-tachyons#62]
I've found that scaling for phone vs tablets is challenging.  While phone resolutions may be similar to tablets due to the high-DPI retina displays, their more extreme landscape / portrait differences change scaling requirements.

Our app scales well for the widths, margins and padding between iPhone and iPads.  However the text scaling is far too small on iPhones.  I propose an optional `fontRem` config that will override the `rem` config just for fonts.  Would you be interested in a PR?

**Comment by fab1an** [comment]
Is this due to dpi-difference? Could you provide a (cropped) screenshot illustrating the problem?

**Comment by peacechen** [comment]
Yes it's primarily due to DPI.  The button sizes and overall spacings scale well using margins and padding.  The text is just too small.  Increasing the `rem` config param increases the text, but makes the buttons and other spacings too large.

![phonefontsizing](https://user-images.githubusercontent.com/6295083/37104165-9c111130-21f1-11e8-8e19-af6f5f62ce40.png)

**Comment by fab1an** [comment]
I‘ll merge this but i want to make sure first it‘s really necessary: 

Do you think this could be automatically applied using https://facebook.github.io/react-native/docs/pixelratio.html

Also I think the real problem is that rnst does not have the media-query dependant spacings like „ns-pa2“ that tachyons.css uses. 

The best way would probably be to adjust the root rem factor to set the font correctly and have media-dependant paddings/margins to account for tablet/phone screenestate. Similar to how it‘s done for websites. 
Which means you have you can set two or three space-properties for small, medium, large and the library applies the best match.

**Comment by peacechen** [comment]
PixelRatio wouldn't help in this case because the relative sizes between fonts and paddings/margins remains fixed.  All the button sizes & spacings continue to scale with the font sizes.

media-query sounds like it could do the job.  It accomplishes the same thing in a slightly different way.  That seems like a bigger task to implement.  Would that require additional config params to specify the small / medium / large cutoffs?

**Comment by fab1an** [comment]
My favourite solution are the media-queries. Cut offs could be fixed or configurable.

I don’t have time to work on that at the moment, do you think you could provide an implementation?

**Comment by peacechen** [comment]
Unfortunately I don't have time to implement media queries either.

It would really help if you would publish the fontRem feature on npm.  This library is set up to transpile the source and create the dist files under lib, so I'm not even able to point to my fork unless I modify the package.json

**Comment by fab1an** [comment]
It think you can use npm link to install your fork locally. 

I‘m thinking about merging this, but implementing basic support for media queries shouldn’t take more than an hour or so. 

I could provide a skeleton but i don‘t have the app for tweaking values. If you could help me with that, that‘ be great. But it included installing a fork nevertheless.

**Comment by peacechen** [comment]
RNST media queries are unnecessary because that can already be configured through `build` as in your example:
```
NativeTachyons.build({
    /* REM parameter is optional, default is 16 */
    rem: screenWidth > 340 ? 18 : 16
}, StyleSheet);
```

The rem calculation can be extended for additional cutoff resolutions.  Adding prefixes on top of that (e.g. `ns-pa2`) would be over-engineering IMHO.

The issue at hand is strictly regarding font scaling relative to space scaling.  The current fixed ratio can't accommodate varying use cases.

**Comment by fab1an** [comment]
I want to help you out there, but I will make sure first rem scaling is necessary. 

If i create a branch with breakpoint code, like I envision, for you, are you willing to install that and give it a try?

**Comment by peacechen** [comment]
Sure I'll help with that

**Comment by peacechen** [comment]
Our app doesn't use line height.  Good to know that there's an issue that you're working on.

**Comment by fab1an** [comment]
Good to know!

**Comment by fab1an** [comment]
Have you checked 3.7 whether everything works?

**Comment by peacechen** [comment]
It's working great.  Thanks for following up.
