### ISSUE TITLE
Line height is broken

### ISSUE THREAD

**Issue by nickdima** [tachyons-css/react-native-style-tachyons#65]
`react-native-style-tachyons` calculates line-height as being in rem but in the tachyons css they are actually unitless numbers, which by [css specification](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#%3Cnumber%3E) get multiplied to the font's computed size.

So, to give an example, if the base font size (rem) is 16px and we have:
```html
<p class="f3 lh-copy">
```
where
```css
.f3 {
    font-size: 1.5rem;
}
.lh-copy {
    line-height: 1.5;
}
```
then the computed styles should be:
```css
font-size: 24px; /*  1.5 * 16px */
line-height: 36px; /* 1.5 * 24px */
```
instead `react-native-style-tachyons` computes them as:
```css
font-size: 24px; /*  1.5 * 16px */
line-height: 24px; /* 1.5 * 16px */
```

So, probably in order to compute them the right way it needs to be aware of the other styles present on the Text element that change the font size. It doesn't sound like an easy fix, does it?

**Comment by fab1an** [comment]
Thanks for the notice.

Well, it's aware of the other "rnt" - styles present on the element. If the user uses a hybrid approch we can't really detect for that. Finding the classes set on nested text-element is also going to be hard.

**Comment by nickdima** [comment]
Yeah, probably the only two options are:
- create line height styles for every font size. eg: `lh_copy__f3`
- make line height be a function like this: `lh_copy("f3")` or similar

**Comment by fab1an** [comment]
I think we'll do the following:
* use the normal style-names and calculate from the font-size given in the class-string
* throw an error if the class-string does contains lh_copy but no explizit font-size

**Comment by nickdima** [comment]
What about when using style arrays instead of class string?

**Comment by fab1an** [comment]
Looking for identity comparison should suffice there.

**Comment by fab1an** [comment]
Hm, no it wouldn‘t, since we don‘t transpile then. Any ideas?
