### ISSUE TITLE
Get the Raw Config File Passed to Style Tachyons

### ISSUE THREAD

**Issue by aswinmohanme** [tachyons-css/react-native-style-tachyons#69]
It would be nice if we could get the raw config object passed to NativeTachyons in the build step. This would help to set the colors independentaly on Components which are not supported.

Also getting the raw values of the Font Families would also be a great help.

**Comment by fab1an** [comment]
Why not assign your config object to a variable you can access elsewhere?

**Comment by aswinmohanme** [comment]
That would be redundant if the library provides the same exact functionality right ?

**Comment by fab1an** [comment]
What you want is having access to your own JS-object everywhere. That is javascript-core-functionality, not what RNST is for. Also the option object might change in the future or use functions that shouldn't be exposed to the user.

I suspect what you really want is not having to add another import in every file. For this you are better of using something like eslint-plugin-auto-import.
