### ISSUE TITLE
Support themes

### ISSUE THREAD

**Issue by jbrodriguez** [tachyons-css/react-native-style-tachyons#7]
I love this library, since this is a problem I'm having in my app, the MAGIC sizes :)

How would you approach having app-wide themes ?

I think it could be done by having the library return the Stylesheet.create(..), but currently it sets the styles property and this makes it behave like a singleton (as far as I can understand).

Any thoughts on this ?

**Comment by fab1an** [comment]
Glad it's of use :).

The library behaves like a singleton, yes. If I reuse styles I tend to factor them out into own react-components. Is that what you meant?

**Comment by jbrodriguez** [comment]
Thanks for the reply @fab1an !

Well, sort of.

What I was visualizing is having separate palettes (one for each theme), then 'somehow' use each  style to display the ui.

**Comment by fab1an** [comment]
So you are talking about colors only?

**Comment by jbrodriguez** [comment]
Right.

With [platform.select](https://facebook.github.io/react-native/docs/platform-specific-code.html) you can account for differences between android/ios.

Your library handles typographic/spacing scaling.

I currently have two stylesheets in my app, the user can select between them.

Each stylesheet has different palettes of colors, as well as ios/android specific code.

Just trying to figure out how to use this library in this context.

**Comment by fab1an** [comment]
I can imagine a couple of ways of approaching this:
* specify two palettes with prefixed names and switch between those in the components
* just specify your colors in a normal stylesheet and mix it with tachyons styling.

**Comment by jbrodriguez** [comment]
Right, that makes sense !

I'll play around with this a bit.

Thanks @fab1an !

**Comment by jbrodriguez** [comment]
@fab1an, I tried a couple of things.

For my use case, I had to change the library a bit, most notably because the singleton wasn't allowing me to have dynamic styling.

What I do in my components is

```javascript
...
const { theme } = this.props.theme
<View style={theme.background}>
</View>
```

Somewhere else in the code, I make 'this.props.theme' point to another stylesheet when the user changes themes.

The changes I made were:

```diff
--    /* placeholder */
--    styles: Object.create(null),
++   /* placeholder */
++  //  styles: Object.create(null),
```

```diff
-- //        _.assign(NativeTachyons.styles, StyleSheet.create(styleSheet));
++         let styles = Object.create(null);
++         _.assign(styles, StyleSheet.create(styleSheet));
++         return styles;
```

```diff
-- export const styles = NativeTachyons.styles;
++ // export const styles = NativeTachyons.styles;
```

This is breaking api, so I didn't create a PR

**Comment by fab1an** [comment]
If you want to you can also just modify the `styles` object returned by RNT.

Or you could defined colors like `colorButton-theme1`, `colorButton-theme2` and use a construct like this:

```javascript
render() {
    return (
         <View cls={`bg-colorButton-${themeName}`}>
         </View>
    )
}
```

Or assign it to the styles object:

```javascript
const themes = {
    theme1: {
          backgroundColor: "ff66ff",
          …
    },
    theme2: {

    },
}

render() {
    return (
         <View styles={[s.flx_i, s.h2, themes.themeName]}>
         </View>
    )
}
```

**Comment by jbrodriguez** [comment]
Thanks ! I'll be testing your suggestions.

**Comment by jbrodriguez** [comment]
I gave it some thought and since I don't want to lose sync with your library, I'll implement something similar to your 2nd suggestion.

I'll have a theme object composed of NativeTachyons.styles + a dynamic color object, which is generated with the same logic you used for the palette (it generates the color, background and border syntax)

```javascript
const theme = {
   styles: NativeTachyons.styles,
   colors: palette['colors1']
}
```

Then I can switch palettes whenever needed
