### ISSUE TITLE
Can't override flexbox properties with defaults?

### ISSUE THREAD

**Issue by collinksmith** [tachyons-css/react-native-style-tachyons#74]
It looks like the default properties (e.g. `justifyContent: 'flex-start'`) aren't available, so there's no way for a parent component to override a child's style for one of those properties.

Here's what I'd like to do:

```
function Child({ props }) {
  return (
    <View style={[s.jcfe, props.style]}></View>
  )
}

function Parent() {
  return (
    <Child style={[s.jcfs]} />
  )
}
```

Correct me if I'm wrong but as far as I can tell that's not possible.

Edit: Of course you can use the regular react-native syntax, but I think it would be nicer to be able to stick with the tachyons classes.

**Comment by fab1an** [comment]
You are right, there are some properties missing.
Could you create a pull-request? We should also switch to the tachyons-names (http://tachyons.io/docs/layout/flexbox/) instead of the abbreviations like "jcfs".

**Comment by fab1an** [comment]
I will not implement this, since I think you should use props if you pass down custom styles to a component like this.
