### ISSUE TITLE
Upgrade to RN 0.56

### ISSUE THREAD

**Issue by nezaidu** [tachyons-css/react-native-style-tachyons#75]
These two commits break wrapping rn view/text 
https://github.com/facebook/react-native/commit/e708010d18f938e2d6b6424cfc9485d8e5dd2800
https://github.com/facebook/react-native/commit/3e534b9aab5156adac67762877b2457408fe8934

**Comment by nezaidu** [comment]
my temp solution 
![image](https://user-images.githubusercontent.com/3225817/43707816-9adfc03e-9971-11e8-9344-a70e3ef1f310.png)

**Comment by timestep** [comment]
+1

**Comment by fab1an** [comment]
Can you open a PR with a fix?

**Comment by fab1an** [comment]
What need to be done on our side here?

**Comment by nezaidu** [comment]
support this thing which is exported here
https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js?spm=5176.blog8184.yqblogcon1.16.mGjd5t

**Comment by fab1an** [comment]
Is this still an issue, can you confirm?
