### ISSUE TITLE
[feature] Provide option to not recurse the children

### ISSUE THREAD

**Issue by James-E-Adams** [tachyons-css/react-native-style-tachyons#76]
Hi there!
I've almost finished implementing optional recursion of children (in my fork), and I was wondering if there is interest in merging it into this repo?

My reasoning is to make the conversion of `cls` -> `style` a little bit more explicit in our project, and then create some wrapped primitives `wrap(Text)`, `wrap(View)` etc to use in place of the defaults. 

Moreover sometimes the recursion isn't 100% effective and doesn't handle the conversion of every classname in tree (no concrete example off the top of my head), so I end up wrapping things multiple times down the tree and that seems inefficient.

I'll post here again once I've got some code/tests up.

**Comment by James-E-Adams** [comment]
https://github.com/James-E-Adams/react-native-style-tachyons/commit/ff2721739cd8e04cb9c7824b65ddd5f80a92dd46

The diff is here - my editor's prettier config is probably different so the diff looks more extreme than it should.

I'm also yet to fix the tests, so 3 of them fail as expected (when the test expects the children's cls prop to have been recursively fixed).

**Comment by fab1an** [comment]
I don't see a general need for this.

If you find an example where the current algorithm misses something, I will consider it a bug and it will be fixed.
