### ISSUE TITLE
'customStyles' documentation

### ISSUE THREAD

**Issue by adkenyon** [tachyons-css/react-native-style-tachyons#78]
I noticed the ability to add custom styles via the source code. Is there any documentation for this feature?

**Comment by fab1an** [comment]
Not yet, that came as part of #64. I might remove this.

**Comment by adkenyon** [comment]
@fab1an you might remove the custom styles? We've found it incredibly useful.

**Comment by fab1an** [comment]
OK, it won't be removed.
