### ISSUE TITLE
FontWeight for custom font in Android

### ISSUE THREAD

**Issue by spuntin** [tachyons-css/react-native-style-tachyons#82]
Is there a way to use fontWeight for a custom font in Android?

This my root:
```
NativeTachyons.build({
    rem: screenWidth > 340 ? 18 : 16,
    fontRem: 20,
    fonts: {
        primary: 'Cabin-Regular'
    },
colors: {
      palette: {
        dGrey: '#56626d',	// dark grey
				
```
and my element:
`<Text style={[s.ff_primary, s.dGrey, s.f3, s.mb4, s.fw6]}>`

Using fw6 breaks the fontFamily styling for android, and reverts to the default font.

Apparently u need to specify the exact weight name for Android:
```
// iOS
{
  fontFamily: 'OpenSans',
  fontWeight: '600',
  fontStyle: 'italic'
}

// Android
{
  fontFamily: 'OpenSans-SemiBoldItalic'
}
```
... but not sure how to incorporate this with tachyons?

**Comment by spuntin** [comment]
So i've added the specific weight name to my configuration:
```
fonts: {
      primary: 'Cabin-Regular',
      primarySemiBold: 'Cabin-SemiBold', // fw6 - needed for Android
      primaryBold: 'Cabin-Bold' // fw7
    },
```

This works, but it means my tachyons fw6, fw7 are now obsolete ... is there a more elegant solution? ... or am i completely missing an easier way to do this? :)

**Comment by fab1an** [comment]
Please try renaming your fonts using this schema:

```
. Cabin_bold.ttf
. Cabin_italic.ttf
. Cabin_semi_bold.ttf
```

See this answer: https://stackoverflow.com/a/38820631/342947
