### ISSUE TITLE
is this still in active development?

### ISSUE THREAD

**Issue by rush86999** [tachyons-css/react-native-style-tachyons#87]
just wondering whether I should use this or not....

**Comment by farwayer** [comment]
@rush86999 You can try https://github.com/farwayer/react-native-tstyles. Still no extra features like style switching (I plan to add it), a bit different from classic tachyons (dimensions in points etc.) and there is no good doc yet. But I actively use it for my projects so the lib will have long term support.

**Comment by adkenyon** [comment]
I'd suggest this `https://github.com/shipt/react-native-tachyons`

**Comment by fab1an** [comment]
I am looking into PRs now.
